import leftNavImage from './assets/leftNavimage.png'
import rightNavImage from './assets/rightnavimage.png'
import pageIcon from './assets/pageIcon.png'
import leftCenterImage from './assets/leftCenter.png'
import pageImage from './assets/pageImage.png'
import loginState from './assets/loginState1.png'
import loginRight from './assets/loginright.png'
import loginBottom from './assets/loginbottom.png'
import backIcon from './assets/backicon.png'
import googleIcon from './assets/Google Icon.png'
import dropicon from './assets/dicon.png'
import dropIconLast from './assets/dicon1.png'
import uparrow from './assets/up-arrow.png'
import downarrow from './assets/down-arrow.png'
import logoutIcon from './assets/logoutIcon.png'
import folderIcon from './assets/folderIcon.png'
import deleteIcon from './assets/deleteIcon.png'
import textIcon from './assets/TextIcon.png'
import videoIcon from './assets/VideoIcon.png'
import photoIcon from './assets/Photo.png'
import gifIcon from './assets/gif.png'
import inputTextIcon from './assets/inputTextIcon.png'
import inputNumberIcon from './assets/inputNumberIcon.png'
import inputEmailIcon from './assets/inputEmailIcon.png'
import inputPhoneIcon from './assets/inputPhoneIcon.png'
import inputDateIcon from './assets/InputDateIcon.png'
import inputRatingIcon from './assets/InputRatingIcon.png'
import inputBtnIcon from './assets/InputBtnIcon.png'
import flagIcon from './assets/flagIcon.png'
import flagWhiteIcon from './assets/Flagewhite.png'
import chatIcon from './assets/BotIcon.jpg'
import sendIcon from './assets/send.png'
import calenderIcon from './assets/calendar.png';

export  {calenderIcon,sendIcon,chatIcon,flagWhiteIcon,flagIcon,inputBtnIcon,inputEmailIcon,inputDateIcon,inputNumberIcon,inputPhoneIcon,inputRatingIcon,inputTextIcon,textIcon,videoIcon,photoIcon,gifIcon,deleteIcon,folderIcon,logoutIcon,uparrow,downarrow,dropIconLast,dropicon,leftCenterImage,leftNavImage,rightNavImage,pageIcon,pageImage,loginState,loginRight,loginBottom,backIcon,googleIcon};